- name: Stable Diffussion - WebUI
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    drive_google: "{{ (lookup('ansible.builtin.env', 'DRIVE_GOOGLE') == 'True') | bool }}"
    mnt_path: "/mnt"
    mnt_sd_path: "{{ mnt_path }}/MyDrive/Stable-diffusion"
    sd_webui: "/content/sd-webui"
    sd_webui_models: "/content/sd-webui/models"
    sd_webui_extensions: "/content/sd-webui/extensions"
    sd_webui_embeddings: "/content/sd-webui/embeddings"
  tasks:
    - name: Manage ZIP
      ansible.builtin.include_tasks:
        file: zip_manage.yml
      with_items:
        - path: "/tmp/memfix.zip"
          dest: "/tmp/"
          url: "https://github.com/nolanaatama/sd-webui/raw/main/memfix.zip"

    - name: Install libunwind8-dev
      ansible.builtin.apt:
        name: libunwind8-dev
        state: present

    - name: Install deb package
      ansible.builtin.apt:
        deb: "{{ item }}"
        allow_downgrade: true
      with_items:
        - /tmp/libtcmalloc-minimal4_2.5-2.2ubuntu3_amd64.deb
        - /tmp/libgoogle-perftools4_2.5-2.2ubuntu3_amd64.deb
        - /tmp/libgoogle-perftools-dev_2.5-2.2ubuntu3_amd64.deb
        - /tmp/google-perftools_2.5-2.2ubuntu3_all.deb

    - name: Install fastapi
      ansible.builtin.pip:
        name: fastapi==0.90.1

    - name: Install torch and other dependencies
      ansible.builtin.pip:
        name:
          - torch==1.13.1+cu116
          - torchvision==0.14.1+cu116
          - torchaudio==0.13.1
          - torchtext==0.14.1
          - torchdata==0.5.1
        extra_args: --extra-index-url https://download.pytorch.org/whl/cu116

    - name: Manage ZIP
      ansible.builtin.include_tasks:
        file: zip_manage.yml
      with_items:
        - path: "/tmp/sd-webui.zip"
          dest: "/content/"
          url: "https://huggingface.co/nolanaatama/webui/resolve/main/sd-webui.zip"

    - name: "Clone {{ item.repo }}"
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        bare: true
      with_items:
        - repo: "https://github.com/nolanaatama/sd-webui-tunnels"
          dest: "{{ sd_webui_extensions }}/sd-webui-tunnels"
        - repo: "https://github.com/Mikubill/sd-webui-controlnet"
          dest: "{{ sd_webui_extensions }}/sd-webui-controlnet"
        - repo: "https://github.com/hnmr293/posex"
          dest: "{{ sd_webui_extensions }}/posex"

    - name: Manage ZIP
      ansible.builtin.include_tasks:
        file: zip_manage.yml
      with_items:
        - path: "/tmp/sd-webui-images-browser.zip"
          dest: "{{ sd_webui_extensions }}"
          url: "https://huggingface.co/nolanaatama/webui/resolve/main/sd-webui-images-browser.zip"

    - name: "Remove {{ item }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ sd_webui_embeddings }}"
        - "{{ sd_webui_extensions }}/sd-webui-controlnet/models"

    - name: "Clone {{ item.repo }}"
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      with_items:
        - repo: "https://huggingface.co/nolanaatama/embeddings"
          dest: "{{ sd_webui_embeddings }}"
        - repo: "https://huggingface.co/nolanaatama/ESRGAN"
          dest: "{{ sd_webui_models }}/ESRGAN"
        - repo: "https://huggingface.co/nolanaatama/models"
          dest: "{{ sd_webui_extensions }}/sd-webui-controlnet/models"
