- name: Stable Diffussion - WebUI
  hosts: localhost
  become: no
  gather_facts: no
  environment:
    LD_PRELOAD: libtcmalloc.so
  vars:
    drive_google: "{{ (lookup('ansible.builtin.env', 'DRIVE_GOOGLE') == 'True') | bool }}"
    mnt_path: "/mnt"
    mnt_sd_path: "{{ mnt_path }}/MyDrive/Stable-diffusion"
    sd_webui: /content/sd-webui
    sd_webui_models: "{{ sd_webui }}/models"
    sd_webui_extensions: "{{ sd_webui }}/extensions"
    sd_webui_embeddings: "{{ sd_webui }}/embeddings"
  tasks:
    - name: Create base 
      when: drive_google
      ansible.builtin.file:
        path: "{{ mnt_sd_path }}"
        state: directory

    - name: Download memfix.zip
      get_url:
        url: https://github.com/nolanaatama/sd-webui/raw/main/memfix.zip
        dest: /tmp/memfix.zip

    - name: Unzip memfix.zip
      unarchive:
        src: /tmp/memfix.zip
        dest: /tmp/

    - name: Install libunwind8-dev
      apt:
        name: libunwind8-dev
        state: present

    - name: Install deb package
      shell: dpkg -i /tmp/*.deb

    - name: Install fastapi
      pip:
        name: fastapi==0.90.1
        state: latest

    - name: Install torch and other dependencies
      pip:
        name:
          - torch==1.13.1+cu116
          - torchvision==0.14.1+cu116
          - torchaudio==0.13.1
          - torchtext==0.14.1
          - torchdata==0.5.1
        extra_args: --extra-index-url https://download.pytorch.org/whl/cu116
        state: latest

    - name: Download sd-webui.zip
      get_url:
        url: https://huggingface.co/nolanaatama/webui/resolve/main/sd-webui.zip
        dest: /content/sd-webui.zip

    - name: Unzip sd-webui.zip
      unarchive:
        src: /content/sd-webui.zip
        dest: /content
        remote_src: yes
        
    - name: Copy needed dirs
      ansible.builtin.copy:
        src: "{{ sd_webui_models }}/"
        dest: "{{ mnt_sd_path }}/"

    - name: Mount drive on 
      ansible.posix.mount:
        src: "{{ mnt_sd_path }}"
        path: "{{ sd_webui_models }}"
        opts: bind
        state: mounted
        fstype: none

    - name: Clone sd-webui-tunnels
      git:
        repo: https://github.com/nolanaatama/sd-webui-tunnels
        dest: /content/sd-webui/extensions/sd-webui-tunnels
        clone: yes

    - name: Clone sd-webui-controlnet
      git:
        repo: https://github.com/Mikubill/sd-webui-controlnet
        dest: /content/sd-webui/extensions/sd-webui-controlnet
        clone: yes

    - name: Clone posex
      git:
        repo: https://github.com/hnmr293/posex
        dest: /content/sd-webui/extensions/posex
        clone: yes

    - name: Download sd-webui-images-browser.zip
      get_url:
        url: https://huggingface.co/nolanaatama/webui/resolve/main/sd-webui-images-browser.zip
        dest: /content/sd-webui/extensions/sd-webui-images-browser.zip

    - name: Unzip sd-webui-images-browser.zip
      unarchive:
        src: /content/sd-webui/extensions/sd-webui-images-browser.zip
        dest: /content/sd-webui/extensions
        remote_src: yes

    - name: Remove existing embeddings folder
      file:
        path: /content/sd-webui/embeddings
        state: absent
      
    - name: Remove existing controlnet models folder
      file:
        path: /content/sd-webui/extensions/sd-webui-controlnet/models
        state: absent
      
    - name: Remove existing sd-webui.zip file
      file:
        path: /content/sd-webui/sd-webui.zip
        state: absent
      
    - name: Remove existing sd-webui-images-browser.zip file
      file:
        path: /content/sd-webui/extensions/sd-webui-images-browser.zip
        state: absent
      
    - name: Clone embeddings repository
      git:
        repo: https://huggingface.co/nolanaatama/embeddings
        dest: /content/sd-webui/embeddings
      
    - name: Clone ESRGAN model repository
      git:
        repo: https://huggingface.co/nolanaatama/ESRGAN
        dest: /content/sd-webui/models/ESRGAN
      
    - name: Clone controlnet model repository
      git:
        repo: https://huggingface.co/nolanaatama/models
        dest: /content/sd-webui/extensions/sd-webui-controlnet/models

