---
- name: "Download {{ item.url }}"
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.path }}"

- name: "Unzip {{ item.url }}"
  ansible.builtin.unarchive:
    src: "{{ item.path }}"
    dest: "{{ item.dest }}"
    remote_src: true
  
- name: "Remove existing {{ item.url }} file"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
...
